apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketdex-deployment
  labels:
    app: rocketdex
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rocketdex
  template:
    metadata:
      labels:
        app: rocketdex
    spec:
      containers:
      - name: rocketdex
        image: kris19334/rocketdex:v1
        ports:
        - containerPort: 8080

