apiVersion: v1
kind: Service
metadata:
  name: rocketdex-service
  labels:
    app: rocketdex
spec:
  type: NodePort
  selector:
    app: rocketdex
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 8080
    nodePort: 31000 
