name: Node.js CI


on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: "Build and Test"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Vitest Coverage Report
        uses: davelosert/vitest-coverage-report-action@v2.8.0
        with:
          vite-config-path: vite.config.ts
